apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sHPAMinReplicaLimit
metadata:
  name: restrict-hpa-minreplicas
spec:
  match:
    kinds:
      - apiGroups: ["autoscaling"]
        kinds: ["HorizontalPodAutoscaler"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - azure-arc
  parameters:
    min: 5
