apiVersion: test.gatekeeper.sh/v1alpha1
kind: ConstraintTemplateSuite
metadata:
  name: hpa-minreplica-limit-suite
tests:
  - name: deny-hpa-with-too-high-minreplicas
    template: k8shpaminreplicalimit
    constraint: ../constraint.yaml
    cases:
      - name: too-high-minreplicas
        object: |
          apiVersion: autoscaling/v2
          kind: HorizontalPodAutoscaler
          metadata:
            name: test-hpa
            namespace: default
          spec:
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: test-deployment
            minReplicas: 10
            maxReplicas: 50
            metrics:
              - type: Resource
                resource:
                  name: cpu
                  target:
                    type: Utilization
                    averageUtilization: 50
        violations:
          - msg: "HPA minReplicas (10) exceeds the allowed maximum of 5."
